name: Deploy to Amazon ECS

# ↓ここが「いつ動くか」の定義です
on:
  push:
    branches: [ "main" ]  # mainブランチにプッシュされた時に動く

permissions:
  id-token: write # これが OIDC を使うために必須！
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ここが OIDC の魔法の部分
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::785621645164:role/GitHubActionsRole # 作ったロールのARN
          aws-region: ap-northeast-1

      # これ以降は今までと同じ（docker build, push など）
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

　　　- name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          IMAGE_TAG=${{ github.sha }}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPOSITORY=hellow-world
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: hellow-world-v2
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: hello-world-task-v2-service-fx1rm85e
          cluster: hello-world-cluster
